# Generated by Django 3.2 on 2022-01-19 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photolog', '0007_alter_post_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='friends',
        ),
        migrations.RemoveField(
            model_name='account',
            name='slug',
        ),
        migrations.AlterField(
            model_name='account',
            name='bio',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='account',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_image'),
        ),
    ]
