# Generated by Django 3.2 on 2022-04-19 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photolog', '0014_addpost'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AddPost',
        ),
    ]
